# kak-tree-sitter default configuration file.
#
# This file is shipped with the kak-tree-sitter binary, you DO NOT HAVE TO COPY IT! If you want to add
# support for a language that is not listed here in your config, you can start with an empty config, as your
# configuration and this default configuration will get merged together.

# List of features to be enabled/disabled. Most of those features can be
# overriden in the user configuration, or even on the CLI — see --with-* flags.
[features]
highlighting = true
text_objects = true

[highlight]
# Top-level highlight capture group declarations. If your grammars uses a capture group that is not defined here, you
# have to add it to the list.
#
# Important: use a dot (.) as delimiter between a parent capture group and its children; e.g.
# top.middle.bottom. This is used internally by KTS to automatically generate face names and values.
groups = [
  "attribute",
  "comment",
  "comment.block",
  "comment.line",
  "comment.unused",
  "constant",
  "constant.builtin",
  "constant.builtin.boolean",
  "constant.character",
  "constant.character.escape",
  "constant.macro",
  "constant.numeric",
  "constant.numeric.float",
  "constant.numeric.integer",
  "constructor",
  "diff.plus",
  "diff.minus",
  "diff.delta",
  "diff.delta.moved",
  "embedded",
  "error",
  "function",
  "function.builtin",
  "function.macro",
  "function.method",
  "function.method.private",
  "function.special",
  "hint",
  "include",
  "info",
  "keyword",
  "keyword.conditional",
  "keyword.control",
  "keyword.control.conditional",
  "keyword.control.except",
  "keyword.control.exception",
  "keyword.control.import",
  "keyword.control.repeat",
  "keyword.control.return",
  "keyword.directive",
  "keyword.function",
  "keyword.operator",
  "keyword.special",
  "keyword.storage",
  "keyword.storage.modifier",
  "keyword.storage.modifier.mut",
  "keyword.storage.modifier.ref",
  "keyword.storage.type",
  "label",
  "load",
  "markup.bold",
  "markup.heading",
  "markup.heading.1",
  "markup.heading.2",
  "markup.heading.3",
  "markup.heading.4",
  "markup.heading.5",
  "markup.heading.6",
  "markup.heading.marker",
  "markup.italic",
  "markup.link.label",
  "markup.link.text",
  "markup.link.url",
  "markup.link.uri",
  "markup.list.checked",
  "markup.list.numbered",
  "markup.list.unchecked",
  "markup.list.unnumbered",
  "markup.quote" ,
  "markup.raw",
  "markup.raw.block",
  "markup.raw.inline",
  "markup.strikethrough",
  "namespace",
  "operator",
  "punctuation",
  "punctuation.bracket",
  "punctuation.delimiter",
  "punctuation.special",
  "special",
  "string",
  "string.escape",
  "string.regexp",
  "string.special",
  "string.special.path",
  "string.special.symbol",
  "string.symbol",
  "tag",
  "tag.error",
  "text",
  "type",
  "type.builtin",
  "type.enum.variant",
  "type.enum.variant.builtin",
  "type.parameter",
  "variable",
  "variable.builtin",
  "variable.other.member",
  "variable.other.member.private",
  "variable.parameter",
  "warning",
]

# astro
[grammar.astro]
source = "bundled"

[language.astro.queries]
source = "bundled"

# awk
[grammar.awk]
source = "bundled"

[language.awk.queries]
source = "bundled"

# bash
[language.bash]
aliases = ["sh"]

[grammar.bash]
source = "bundled"

[language.bash.queries]
source = "bundled"

# bass
# TODO

# beancount
# TODO

# bibtex
[grammar.bibtex]
source = "bundled"

[language.bibtex.queries]
source = "bundled"

# bicep
# TODO

# c
[grammar.c]
source = "bundled"

[language.c.queries]
source = "bundled"

# cabal
# TODO

# cairo
# TODO

# capnp
# TODO

# clojure
# TODO

# cmake
[grammar.cmake]
source = "bundled"

[language.cmake.queries.source.git]
url = "https://github.com/helix-editor/helix"
pin = "7275b7f85014aad7e15d4987ec4f2249572eecfb"

# comment
[grammar.comment]
source = "bundled"

[language.comment.queries]
source = "bundled"

# common-lisp
# TODO

# cpon
# TODO

# cpp
[grammar.cpp]
source = "bundled"

[language.cpp.queries]
source = "bundled"

# crystal
[grammar.crystal]
source = "bundled"

[language.crystal.queries]
source.git.url = "https://github.com/helix-editor/helix"
source.git.pin = "c96642125f87b7f2ca186662c5885d129262133e"

# c-sharp
[grammar.csharp]
source = "bundled"

[language.csharp.queries.source.git]
url = "https://github.com/helix-editor/helix"
pin = "7275b7f85014aad7e15d4987ec4f2249572eecfb"

[language.csharp.queries]
path = "runtime/queries/c-sharp"

# css
[grammar.css]
source = "bundled"

[language.css.queries]
source = "bundled"

# cue
# TODO

# d
# TODO

# dart
# TODO

# devicetree

[grammar.devicetree]
source = "bundled"

[language.devicetree.queries]
source = "bundled"

# dhall
# TODO

# diff
[grammar.diff]
source = "bundled"

[language.diff.queries]
source = "bundled"

# dockerfile
# TODO

# dot
# TODO

# dtd
# TODO

# ecma
# TODO

# edoc
# TODO

# eex
# TODO

# ejs
# TODO

# elixir
[grammar.elixir]
source = "bundled"

[language.elixir.queries]
source = "bundled"

# elm
# TODO

# elvish
# TODO

# env
# TODO

# erb
# TODO

# erlang
# TODO

# esdl
# TODO

# fish
[grammar.fish]
source = "bundled"

[language.fish.queries]
source = "bundled"

# fortran
# TODO

# gdscript
# TODO

# git-attributes
# TODO

# git-commit
[grammar.git-commit]
source = "bundled"

[language.git-commit.queries]
source = "bundled"

# git-config
# TODO

# git-ignore
# TODO

# git-rebase
# TODO

# gleam
# TODO

# glsl
[grammar.glsl]
source = "bundled"

[language.glsl.queries]
source = "bundled"

# go
[grammar.go]
source = "bundled"

[language.go.queries]
source = "bundled"

# godot-resource
# TODO

# gomod
# TODO

# gotmpl
# TODO

# gowork
# TODO

# graphql
# TODO

# hare
# TODO

# haskell
[grammar.haskell]
source = "bundled"

[language.haskell.queries]
source = "bundled"

# hcl
# TODO

# heex
# TODO

# hosts
# TODO

# html
[grammar.html]
source = "bundled"

[language.html.queries.source.git]
url = "https://github.com/helix-editor/helix"
pin = "7275b7f85014aad7e15d4987ec4f2249572eecfb"

# hurl
# TODO

# hyprlang
[grammar.hyprlang]
source = "bundled"

[language.hyprlang.queries]
source = "bundled"

# iex
# TODO

# ini
[grammar.ini]
source = "bundled"

[language.ini.queries]
source = "bundled"

# java
[grammar.java]
source = "bundled"

[language.java.queries]
source = "bundled"

# javascript
[grammar.javascript]
source = "bundled"

[language.javascript.queries]
source = "bundled"

# jsdoc
# TODO

# json
[grammar.json]
source = "bundled"

[language.json.queries]
source = "bundled"

# jsonc
[language.jsonc]
grammar = "json"

[language.jsonc.queries]
source = "bundled"

# jsonnet
# TODO

# jsx
[language.jsx]
grammar = "javascript"

[language.jsx.queries]
source = "bundled"

# julia
[grammar.julia]
source = "bundled"

[language.julia.queries]
source = "bundled"

# just
[grammar.just]
source = "bundled"

[language.just.queries]
source = "bundled"


# kdl
[grammar.kdl]
source = "bundled"

[language.kdl.queries]
source = "bundled"

# koka
[grammar.koka]
source = "bundled"

[language.koka.queries]
source = "bundled"

# kotlin
[grammar.kotlin]
source = "bundled"

[language.kotlin.queries]
source = "bundled"

# latex
[grammar.latex]
source = "bundled"

[language.latex.queries]
source = "bundled"

# lean
[grammar.lean]
source = "bundled"

[language.lean.queries]
source = "bundled"

# ledger
# TODO

# llvm
[grammar.llvm]
source = "bundled"

[language.llvm.queries]
source = "bundled"

# llvm-mir
# TODO

# llvm-mir-yaml
# TODO

# lua
[grammar.lua]
source = "bundled"

[language.lua.queries]
source = "bundled"

# make
[grammar.make]
source = "bundled"

[language.make.queries]
source = "bundled"

# markdoc
# TODO

# markdown
[grammar.markdown]
source = "bundled"

[language.markdown.queries]
source = "bundled"

# markdown.inline
[grammar."markdown.inline"]
source = "bundled"

[language."markdown.inline".queries]
source = "bundled"

# matlab
# TODO

# mermaid
[grammar.mermaid]
source = "bundled"

[language.mermaid.queries]
source = "bundled"

# meson
# TODO

# msbuild
# TODO

# nasm
# TODO

# nickel
# TODO

# nim
[grammar.nim]
source = "bundled"

[language.nim.queries]
source = "bundled"

# nix
[grammar.nix]
source = "bundled"

[language.nix.queries]
source = "bundled"

# nu
[grammar.nu]
source = "bundled"

[language.nu.queries]
source = "bundled"

# ocaml

[grammar.ocaml]
source = "bundled"

[language.ocaml.queries]
source = "bundled"

# ocaml-interface

[grammar."ocaml-interface"]
source = "bundled"

[language.ocaml-interface.queries]
source = "bundled"

# odin
# TODO

# opencl
# TODO

# openscad
# TODO

# org
# TODO

# pascal
# TODO

# passwd
# TODO

# pem
# TODO

# perl
# TODO

# pest
[grammar.pest]
source = "bundled"

[language.pest.queries]
source = "bundled"

# php
# TODO

# po
# TODO

# ponylang
# TODO

# prisma
# TODO

# protobuf
# TODO

# prql
# TODO

# purescript
[grammar.purescript]
source = "bundled"

[language.purescript.queries]
source = "bundled"

# python
[grammar.python]
source = "bundled"

[language.python.queries]
source = "bundled"

# qml
[grammar.qmljs]
source = "bundled"

[language.qmljs.queries]
source = "bundled"


[language.qmljs]
aliases = ["qml"]

# r
# TODO

# racket
# TODO

# regex
# TODO

# rego
# TODO

# rescript
# TODO

# rmarkdown
# TODO

# robot
# TODO

# ron
# TODO

# rst
# TODO

# ruby
[grammar.ruby]
source = "bundled"

[language.ruby.queries.source.git]
url = "https://github.com/helix-editor/helix"
pin = "7275b7f85014aad7e15d4987ec4f2249572eecfb"

# rust
[grammar.rust]
source = "bundled"

[language.rust.queries]
source = "bundled"

# rust-format-args
[grammar.rust-format-args]
source = "bundled"

[language.rust-format-args.queries.source.git]
url = "https://github.com/helix-editor/helix"
pin = "1023e8f96482f725465bf2bc059e274f6ac0bb26"

# sage
# TODO

# scala
# TODO

# scheme
[grammar.scheme]
source = "bundled"

[language.scheme.queries]
source = "bundled"

# scss
[grammar.scss]
source = "bundled"

[language.scss.queries]
source = "bundled"

# slint
# TODO

# smithy
# TODO

# sml
# TODO

# solidity
# TODO

# sql
# TODO

# sshclientconfig
# TODO

# starlark
# TODO

# svelte
# TODO

# sway
# TODO

# swift
# TODO

# tablegen
# TODO

# task
[grammar.task]
source = "bundled"

[language.task.queries]
source = "bundled"

# tfvars
# TODO

# toml
[grammar.toml]
source = "bundled"

[language.toml.queries]
source = "bundled"

# tsq
# TODO

# tsx
[language.tsx]
grammar = "typescript"

[language.tsx.queries]
source = "bundled"

# twig
# TODO

# typescript
[grammar.typescript]
source = "bundled"

[language.typescript.queries]
source = "bundled"

# typst
[language.typst]
aliases = ["typ", "typc"]

[grammar.typst]
source = "bundled"

[language.typst.queries]
source = "bundled"

# ungrammar
# TODO

# unison
[grammar.unison]
source = "bundled"

[language.unison.queries]
source = "bundled"

# uxntal
# TODO

# v
# TODO

# vala
# TODO

# verilog
[grammar.verilog]
source = "bundled"

[language.verilog.queries]
source = "bundled"

# vhdl
# TODO

# vhs
# TODO

# vue
[grammar.vue]
source = "bundled"

[language.vue.queries.source.git]
url = "https://github.com/helix-editor/helix"
pin = "205e7ece70c52a7d921ea014e1017c41488e37e5"

# wast
# TODO

# wat
# TODO

# wgsl
# TODO

# wit
# TODO

# xit
# TODO

# xml
[grammar.xml]
source = "bundled"

[language.xml.queries]
source = "bundled"

# yaml
[grammar.yaml]
source = "bundled"

[language.yaml.queries]
source = "bundled"

# yuck
# TODO

# zig
[grammar.zig]
source = "bundled"

[language.zig.queries]
source = "bundled"
